### ISSUE TITLE
Hard to read the text on the landing page

### ISSUE THREAD

**Issue by it-slav** [SUSE-Developer-Community/sandbox-welcome-content#94] opened 2020-03-30 12:52 UTC
I have a hard time reading the text with grey text and background brown/grey sand. See attached pic.

![image](https://user-images.githubusercontent.com/9952712/77914259-ec65a780-7295-11ea-9349-8a4196c4e608.png)

**Comment by timirnich** [comment] 2020-03-30 12:58
Duplicate of https://github.com/SUSE-Developer-Community/explore.suse.dev/issues/20, closing here.

**Closed as completed by timirnich** 2020-03-30 12:58 UTC
